static_bhp/app/__init__.py
from flask import Flask

def create_app():
    """Initializes the flask application
    Imports from views.py
    registers physical_properties as a blueprint
    
    Returns:
        app
    """
    app = Flask(__name__)

    from .views import physical_properties
    app.register_blueprint(physical_properties)

    return app

static_bhp/app/views.py
from flask import Blueprint, render_template, request
from app.physical_properties.conversions import evaluate_scrhs
from app.physical_properties.staticbhp import StaticBHP
from app.physical_properties.pseudoreduced_properties import pseudo_reduced_temp, pseudo_reduced_wellhead_pressure
from app.physical_properties.pseudocritical_properties import natural_gas_systems, natural_gas_systems2

physical_properties = Blueprint("physical_properties", __name__, template_folder="physical_properties")

@physical_properties.route("/")
def index():
    """Renders the index page"""
    return render_template("index.html")

@physical_properties.route("/calculate_properties", methods=["POST"])
def calculate_properties():
    """POST inputs from user
    
    Returns:
        Renders the result page and pass computed values of gas properties
    """

    try:
        # Get input values from the form
        well_depth = float(request.form.get("well_depth"))
        temp_avg_sys = float(request.form.get("temp_avg_sys"))
        gas_specific_gravity = float(request.form.get("gas_specific_gravity"))
        static_wellhead_pressure = float(request.form.get("static_wellhead_pressure"))

        # Calculate pseudocritical properties of the gas system
        tpc_natural_gas_systems = natural_gas_systems(gas_specific_gravity)
        ppc_natural_gas_systems = natural_gas_systems2(gas_specific_gravity)

        # Call functions from physical_properties/ with the input values
        scrhs = evaluate_scrhs(gas_specific_gravity, well_depth, temp_avg_sys)
        reduced_temp = pseudo_reduced_temp(temp_avg_sys, gas_specific_gravity)
        reduced_pressure = pseudo_reduced_wellhead_pressure(static_wellhead_pressure, gas_specific_gravity)

        # Creates an instance of the StaticBHP class
        sbhp = StaticBHP()

        static_bhp_result = sbhp.print_staticbhp(reduced_temp, reduced_pressure, scrhs, gas_specific_gravity)

        return render_template(
            "result.html",
            scrhs=scrhs,
            reduced_temp=reduced_temp,
            reduced_pressure=reduced_pressure,
            static_bhp_result=static_bhp_result,
            tpc_natural_gas_systems=tpc_natural_gas_systems,
            ppc_natural_gas_systems=ppc_natural_gas_systems,
            static_wellhead_pressure=static_wellhead_pressure,
        )
    except Exception as e:
        return f'Error: Ensure that all input fields are satisfied and are within the given in range - {e}'

static_bhp/app/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Error</h1>
    <p>{{ error_message }}</p>
</body>
</html>

static_bhp/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Physical Properties</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <h1>Physical Properties of The Gas Well</h1>
    <form action="{{ url_for('physical_properties.calculate_properties') }}" method="post">
        <p><label for="well_depth">Well Depth:</label>
        <input type="text" name="well_depth" required></p>

        <p><label for="temp_avg_sys">Average Temperature (Fahrenheit):</label>
        <input type="text" name="temp_avg_sys" required></p>

        <p><label for="gas_specific_gravity">Gas Specific Gravity:</label>
        <input type="text" name="gas_specific_gravity" required></p>

        <p><label for="static_wellhead_pressure">Wellhead Pressure (psia):</label>
        <input type="text" name="static_wellhead_pressure" required></p>

        <button type="submit">Calculate</button>
    </form>
</body>
</html>

static_bhp/app/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <h1>Calculation Result</h1>
    <p>Static Wellhead Pressure: {{ static_wellhead_pressure }}</p>
    <p>Sukkar and Cornell Integral RHS: {{ scrhs }}</p>
    <p>Pseudo-Reduced Temperature: {{ reduced_temp }}</p>
    <p>Pseudo-Reduced Wellhead Pressure: {{ reduced_pressure }}</p>
    <p>Pseudocritical Temperature (Natural Gas Systems): {{ tpc_natural_gas_systems }}</p>
    <p>Pseudocritical Pressure (Natural Gas Systems): {{ ppc_natural_gas_systems }}</p>
    <!-- <p>pseudo_reduced_bhp: {{ pseudo_reduced_bhp }}</p>
    <p>pseudo_reduced_bhp2: {{ pseudo_reduced_bhp2 }}</p>
    <p>check truncated ppr: {{ check }}</p>
    <p>locate cell with ppr: {{ locate_ppr }}</p>
    <p>ppr value: {{ ppr_value}}</p>
    <p>deno_sciv value: {{ deno_sciv }}</p>
    <p>pivot_sciv value: {{ pivot_sci }}</p>
    <p>unknown_sciv value: {{ unknown_sciv }}</p> -->
    <p>Estimate ==> {{ static_bhp_result }}</p>

</body>
</html>